#102 - Migrate lib to typescript
TableRise/database-seeder pull request #1
Opened 2023-08-16 17:14 UTC by RasecMH

2023-08-16 18:12 UTC, Adson-Gomes-Oliveira requested changes

2023-08-16 18:12 UTC, Adson-Gomes-Oliveira commented on package.json
> +    "nodemon": "3.0.1",
Porque o nodemon?

2023-08-16 18:12 UTC, Adson-Gomes-Oliveira commented on package.json
> +    "ts-node": "10.9.1",
Porque o ts-node?

2023-08-16 18:12 UTC, Adson-Gomes-Oliveira commented on package.json
>    }
Adicionar ao final do package json uma ultima key:

"files": [
    "/dist"
  ]

2023-08-16 18:12 UTC, Adson-Gomes-Oliveira commented on package.json
>    "main": "index.js",
Adicionar "types": "dist/index.d.ts", depois de main.

2023-08-16 18:12 UTC, Adson-Gomes-Oliveira commented on tsconfig.json
> +  "include": ["src/**/*"]
Trocar para: "exclude": ["node_modules", "dist"]

2023-08-16 18:45 UTC, RasecMH commented on package.json
> +    "nodemon": "3.0.1",
Instalei para testar a lib e esqueci de deletar.

2023-08-16 18:45 UTC, RasecMH commented on package.json
> +    "ts-node": "10.9.1",
Mesmo que nodemon.

2023-08-16 18:45 UTC, RasecMH commented on package.json
>    }
Adicionado.

2023-08-16 18:45 UTC, RasecMH commented on tsconfig.json
> +  "include": ["src/**/*"]
Modificado.

2023-08-16 18:46 UTC, RasecMH commented on package.json
>    "main": "index.js",
Adicionado.

2023-08-17 01:17 UTC, Adson-Gomes-Oliveira approved these changes

2023-08-17 13:28 UTC, merged